### ISSUE TITLE
有想过做成类似vue-cli的命令行工具么？

### ISSUE THREAD

**Issue by ShupingHe** [zoux/vue-preset#1]

**Comment by ShupingHe** [comment]
@zoux

**Comment by zoux** [comment]
hello～

这两天刚好在做基于该模版的 vue-cli 3 插件。

项目地址参加：https://github.com/zoux/vue-cli-plugin-template

**Comment by zoux** [comment]
关于类似 vue-cli 的命令行工具，建议 clone vue-cli 的项目代码
